spring:
  profiles:
    active: false

  security:
    user:
      name: admin
      password: admin

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/safewoman
    password: postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

jwt:


server:
    port: 8080

